<?php
$array = array("A");
array_push($array, "B");
echo "Array awal: ";
print_r(array("A"));
echo "<br>Hasil array_push: ";
print_r($array);
echo "<br><br>";
$array1 = array("A", "B");
$array2 = array("C");
$hasil_merge = array_merge($array1, $array2);
echo "Array awal: ";
print_r($array1);
echo "<br>Hasil array_merge: ";
print_r($hasil_merge);
echo "<br><br>";
$data = array("x"=>1, "y"=>2);
echo "Array awal: ";
print_r($data);
echo "<br>Hasil array_values: ";
print_r(array_values($data));
echo "<br><br>";
$huruf = array("A", "B", "C");
echo "Mencari B pada array: ";
print_r($huruf);
echo "<br>Hasil array_search: ";
echo array_search("B", $huruf);
echo "<br><br>";
$angka = array(0, 1, false, 2, "", 3, "array");
echo "Array awal: ";
print_r($angka);
echo "<br>Hasil array_filter: ";
print_r(array_filter($angka));
echo "<br><br>";
$nilai = array(3,1,2);
echo "Array awal: ";
print_r($nilai);
sort($nilai);
echo "<br>Hasil sort: ";
print_r($nilai);
rsort($nilai);
echo "<br>Hasil rsort: ";
print_r($nilai);
echo "<br><br>";
$student = array("Peter"=>35, "Ben"=>37, "Joe"=>43);
echo "Array awal: ";
print_r($student);
asort($student);
echo "<br>Hasil asort: ";
print_r($student);
arsort($student);
echo "<br>Hasil arsort: ";
print_r($student);
ksort($student);
echo "<br>Hasil ksort: ";
print_r($student);
krsort($student);
echo "<br>Hasil krsort: ";
print_r($student);
?>